knewton:
    baseurl:
    title: Project Name
    theme_color: '#21243c'
    language: en-US 
    header:
        logo:
            text:
            image: true
        nav:
            - item_name: Home
              item_url: /
            - item_name: Adaptive Content
              item_url: /default
            - item_name: Adaptive Products
              item_url: /product
            - item_name: Adaptive Development
              item_url: /product
    footer:
        logo:
            text: Project name
            image:
        text: Copyright &copy; 2018. - Project name <br>All rights reserved.
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your Disqus forum shortname to activate comments site-wide

# Defining collections
collections:
    documentation:
        output: true
    product:
        output: true

# Defining defaults
defaults:
    -
        scope:
            path: ''
            type: 'documentation'
        values:
            layout: 'documentation-single'

# SASS settings
sass:
    sass_dir: ./knewton-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./knewton-theme/_layouts
includes_dir: ./knewton-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
