knewton:
    baseurl: /some-docsite
    title: dev.knewton.com - Knewton Enterprise Platform Documentation
    header:
        logo:
            text:
            image: true
        nav:
            - item_name: Home
              item_url: /
            - item_name: Adaptive Products
              item_url: /adaptive-products
            - item_name: Adaptive Content
              item_url: /adaptive-content
        cta:
            label: API Documentation
            url: /documentation
            icon: folder # https://feathericons.com
    footer:
        links:
            - url: "https://www.knewton.com"
              text: "Build with Knewton"
              external: true
            - url: "https://www.knewton.com"
              text: "Legacy Documentation"
              external: false
            - url: "https://www.knewton.com"
              text: "Knewton Alta"
              external: false
    google_analytics:
        tracking_code: UA-23652421-3

# Defining collections
collections:
    documentation:
        output: true
    product:
        output: true    
    content:
        output: true

# Defining defaults
defaults:
    -
        scope:
            path: ''
            type: 'documentation'
        values:
            layout: 'documentation-single'

# SASS settings
sass:
    sass_dir: ./knewton-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./knewton-theme/_layouts
includes_dir: ./knewton-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
