knewton:
    baseurl: /some-docsite
    title: dev.knewton.com Knewton Enterprise Platform
    header:
        logo:
            text:
            image: true
        nav:
            - item_name: Home
              item_url: /
            - item_name: Adaptive Products
              item_url: /adaptive-products
            - item_name: Adaptive Content
              item_url: /adaptive-content
        cta:
            label: API Documentation
            url: /documentation
            icon: folder # https://feathericons.com
    footer:
        logo:
            text: dev.knewton.com
            image:
        text: Copyright &copy; 2020. - dev.knewton.com <br>All rights reserved.
    google_analytics:
        tracking_code: 

# Defining collections
collections:
    documentation:
        output: true
    product:
        output: true    
    content:
        output: true

# Defining defaults
defaults:
    -
        scope:
            path: ''
            type: 'documentation'
        values:
            layout: 'documentation-single'

# SASS settings
sass:
    sass_dir: ./knewton-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./knewton-theme/_layouts
includes_dir: ./knewton-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
